apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vsphere-csi-driver.yml

images:
  - name: registry.k8s.io/sig-storage/csi-attacher
    newName: harbor.mgmt.hss.int/sig-storage/csi-attacher # Specify the new registry or repository
    newTag: v4.8.1  # Update to the desired image tag

  - name: registry.k8s.io/sig-storage/csi-resizer
    newName: harbor.mgmt.hss.int/sig-storage/csi-resizer # Specify the new registry or repository
    newTag: v1.12.0  # Update to the desired image tag

  - name: registry.k8s.io/csi-vsphere/driver
    newName: harbor.mgmt.hss.int/csi-vsphere/driver # Specify the new registry or repository
    newTag: registry.k8s.io/csi-vsphere/syncer:v3.5.0  # Update to the desired image tag

  - name: registry.k8s.io/sig-storage/livenessprobe
    newName: harbor.mgmt.hss.int/sig-storage/livenessprobe # Specify the new registry or repository
    newTag: v2.15.0  # Update to the desired image tag

  - name: registry.k8s.io/csi-vsphere/syncer
    newName: harbor.mgmt.hss.int/csi-vsphere/syncer # Specify the new registry or repository
    newTag: v3.5.0  # Update to the desired image tag

  - name: registry.k8s.io/sig-storage/csi-provisioner
    newName: harbor.mgmt.hss.int/sig-storage/csi-provisioner # Specify the new registry or repository
    newTag: v4.0.1  # Update to the desired image tag

  - name: registry.k8s.io/sig-storage/csi-snapshotter
    newName: harbor.mgmt.hss.int/sig-storage/csi-snapshotter # Specify the new registry or repository
    newTag: v8.2.0  # Update to the desired image tag
